#no es posible dentro de location root con la misma direccion, tienen que ser un nivel mas arriba.
#client_max_body_size debe ser a nivel server
#location anidadas no tienen sentido, mejor dos location 1->/uploads 2->/uploads/docs
#la directiva listen es obligatoria

server {
    listen 8080;
    client_max_body_size 10485760; #10 * 1024 * 1024 -> 10MB (el parser lo trata como bits sin sufijo.)
    error_page 404 ./html/404.html;

    location / {
        root ./html;
        index index.html;
        methods GET;
        autoindex off;
    }

    location /oldpage.html {
        return 301 redirection.html;
    }

    location /uploads {
        root ./html;
        methods GET POST DELETE;
        upload_store ./html/uploads;
        autoindex on;
    }
}
