#no es posible dentro de location root con la misma direccion, tienen que ser un nivel mas arriba.
#client_max_body_size debe ser a nivel server
#location anidadas no tienen sentido, mejor dos location 1->/uploads 2->/uploads/docs
#la directiva listen es obligatoria


server {
    listen 8080;
    client_max_body_size 10gb;
    error_page 404 ./html/err/404.html;
    error_page 405 ./html/err/405.html;

    location / {
        root ./html;
        index index.html;
        methods GET;
        autoindex off;
    }

    location /notAllowed {
        methods POST;
    }

    location /oldpage.html {
        return 301 /redirection.html;
    }

    location /uploads {
        root ./html;
        methods GET POST DELETE;
        upload_store ./html/uploads;
        autoindex on;
    }

    location /cgi-bin {
    root ./html;
    methods GET POST;
    cgi_extension .py /usr/bin/python3;
    cgi_extension .sh /usr/bin/bash;
	}
}

server {
    listen 8090;
    client_max_body_size 10gb;
    error_page 404 ./html/err/404.html;

    location / {
        root ./html;
        index index.html;
        methods GET;
        autoindex on;
    }

    location /oldpage.html {
        return 301 /redirection.html;
    }

    location /uploads {
        root ./html;
        methods GET POST DELETE;
        upload_store ./html/uploads;
        autoindex on;
    }
    
    location /cgi-bin {
    root ./html;
    methods GET POST;
    cgi_extension .py /usr/bin/python3;
    cgi_extension .sh /usr/bin/bash;
	}
}
